config/routes.rb
Rails.application.routes.draw do

  resource :player , only: [ :index ] do
    get 'music_cmd'  => 'player#music_cmd'
    post 'music_cmd_post' => 'player#music_cmd'
    get 'load_page' => 'player#load_page'
    get 'change_play_list' => 'player#change_play_list'
    get 'suggest' => 'player#suggest'
  end

  resources :songs do
    get 'load_page' , on: :collection
    get 'music_cmd', on: :collection
    get  'add_to_queue', on: :collection
    post 'add_to_queue', on: :collection
    get 'edit_multiple', on: :collection
    post 'update_multiple', on: :collection
    get 'download'
    get 'download_multiple', on: :collection
    get 'download_playlist', on: :collection
    post 'delete_multiple', on: :collection
    get 'suggest' , on: :collection
    get 'excel' , on: :collection
  end

  resources :artists , only: [ :index , :edit , :update , :show ] do
    get 'search_wikipedia' , on: :collection
    get 'get_wikipedia_image' , on: :collection
    get 'load_page' , on: :collection
    post 'join'
    get 'suggest' , on: :collection
    post 'add_to_queue', on: :collection
    get 'download_playlist', on: :collection
    get 'download_multiple', on: :collection
  end

  resources :albums , only: [ :index , :show , :edit , :update ] do
    get 'suggest' , on: :collection
    get 'load_page' , on: :collection
    get 'suggest' , on: :collection
    post 'add_to_queue', on: :collection
    get 'download_playlist', on: :collection
    get 'download_multiple', on: :collection
  end

  resources :play_lists

  resources :radios do
    get 'create_spanish_radios', on: :collection
  end

  resources :tasks , only: [ :index , :new , :create ]

  resource :setting , only: [ :edit , :update ] do
    post 'speech'
    get 'recalculate_metadata'
    get 'start_music_service'
    get 'stop_music_service'
    get 'shutdown'
    get 'mount_usb_drive'
  end

  resource :tools , only: [] do
    get 'youtube', on: :collection
    post 'get_youtube', on: :collection
    get 'duplicated_songs', on: :collection
    get 'readme' , on: :collection
  end

  resources :logs , only: [ :index , :show ] do
    get 'load_page' , on: :collection
    post 'clear' , on: :collection
  end

  root 'player#index'

end

app/controllers/player_controller.rb
load "#{Rails.root}/lib/music/client.rb"
load "#{Rails.root}/lib/music/cmd_result.rb"
load "#{Rails.root}/lib/active_record_utils/bulk_operation.rb"
load "#{Rails.root}/lib/active_record_utils/arutils.rb"

# Main page
class PlayerController < MusicBaseController

  include SuggestModule

  # Renders the player page
  def index
    render_index
  end

  # Executes a command on the music server
  # [+params[:cmd]+] The command to execute on the music server. +'refresh'+
  # to refresh the player state
  def music_cmd

    # The command 'refresh' does not execute any command: It only refresh
    # the player state on the view
    if params[:cmd] != 'refresh'

      # Execute the command
      result = execute_music_cmd_from_parms

      # Feedback the user?
      if result && ( result.status == :error || result.info )
        @toast = result
      end

      # Refresh the production queue?
      if params[:cmd] == 'remove_queue_songs'
         @refresh_queue = true
      end

    end

    # Render the response
    respond_to do |format|
      format.html { render_index }
      format.js do
        load_player_state
        load_reproduction_queue if @refresh_queue
      end
    end

  end

  def load_page
    load_page_template(load_reproduction_queue)
  end

  # Change the current play list
  # [+params[:play_list_id]+] The PlayList id to set
  def change_play_list

    list_id = params[:play_list_id].to_i
    puts "*** change_play_list.list_id: #{list_id.inspect}"

    if list_id == PlayList.reproduction_queue.id
      # Play mp3 on speakers
      puts "*** Set play mp3 on speakers"
      cookies.permanent[:mode] = PLAY_ON_SPEAKERS_MODE
      cookies.permanent[:source] = PlayerState::SOURCE_FILE_SONGS
      cookies.permanent[:play_list_id] = list_id
      # Send the new mode to the play server
      execute_music_cmd( :change_mode , { mode: PlayerState::SOURCE_FILE_SONGS } )

    elsif list_id == -1
      # Play radio on speakers
      puts "*** Set play radio on speakers"
      cookies.permanent[:mode] = PLAY_ON_SPEAKERS_MODE
      cookies.permanent[:source] = PlayerState::SOURCE_RADIO
      # Send the new mode to the play server
      execute_music_cmd( :change_mode , { mode: PlayerState::SOURCE_RADIO } )

    elsif list_id == -2
      # Play radio with streaming
      puts "*** Set play mp3 on streaming (#{STREAMING_MODE}.inspect)"
      cookies.permanent[:mode] = STREAMING_MODE
      cookies.permanent[:source] = PlayerState::SOURCE_RADIO

    else
      # Play mp3 on streaming
      puts "*** Set play mp3 on streaming (#{STREAMING_MODE}.inspect)"
      cookies.permanent[:mode] = STREAMING_MODE
      cookies.permanent[:source] = PlayerState::SOURCE_FILE_SONGS
      cookies.permanent[:play_list_id] = list_id
    end

    redirect_to action: 'index'
  end


  # Action to suggest names on the filter
  def suggest
    suggest_classes( [ Song , Artist , Album ] )
  end

  ##################################################################
  protected
  ##################################################################

  def get_filter_changed_response
    get_filter_changed_response_base(load_reproduction_queue, :queue)
  end
  helper_method :get_filter_changed_response

  def load_reproduction_queue
    load_player_state

    if @player_state.mode == PlayerState::SOURCE_RADIO
      # Playing radio
      return @radios if @radios
      @radios = Radio.all.order(:name)
      # Get the content of the artist images directory
      @images_list = ImagesModule.images_dir_list
      return @radios
    else
      # Playing files
      return @queue_songs if @queue_songs
      # Get the songs page
      @queue_songs = SongsSearch.new( current_play_list )
      @queue_songs.apply_filter(params[:filter] ? params[:filter] : params)
      @queue_songs.page_size = 100
      @queue_songs.page_index = params[:page_index].to_i if params[:page_index]
      return @queue_songs
    end

  end

  def render_index
    load_player_state

    # Selected value on the mode combo
    if !@player_state.is_streaming? && @player_state.mode == PlayerState::SOURCE_RADIO
      @play_list_id = -1
    elsif @player_state.is_streaming? && @player_state.mode == PlayerState::SOURCE_RADIO
      @play_list_id = -2
    else
      @play_list_id = @player_state.play_list.id
    end

    # Load reproduction queue
    load_reproduction_queue

    # Load play lists
    @play_lists = PlayList.all.order(:name).to_a

    # Get and remove the reproduction queue of the server speakers:
    speakers_pl = @play_lists.find{ |p| p.name == PlayList::REPRODUCTION_QUEUE_NAME }
    @play_lists.delete( speakers_pl ) if speakers_pl

    # Change streaming playlists description
    @play_lists.each { |p| p.name = "Streaming - '#{p.name}' play list" }

    # Add radio mode (streaming)
    radio_item = PlayList.new
    radio_item.id = -2
    radio_item.name = 'Streaming - Play radio'
    @play_lists << radio_item

    if speakers_pl
      speakers_pl.name = 'Server speakers - Play MP3'
      @play_lists << speakers_pl
    end

    # Add radio mode (speakers)
    radio_item = PlayList.new
    radio_item.id = -1
    radio_item.name = 'Server speakers - Play radio'
    @play_lists << radio_item

    render 'index'

  end

end

app/helpers/player_helper.rb
module PlayerHelper
end

app/views/player/_player.html.erb
<div>
  <% if @player_state.playing? %>
    <div>
      <dl style="margin-bottom:0">
        <% if @player_state.mode == PlayerState::SOURCE_FILE_SONGS %>
          <%# Artist image %>
          <div style="float: right">
            <%= render 'artists/artist_image' ,
              { artist: @current_song.artist , span_class: 'img_container' } %>
          </div>
          <%# Song information %>

            <dt>Artist</dt>
            <dd>
              <%= link_to @current_song.artist.name , artist_path(@current_song.artist) %>
            </dd>

            <dt>Album</dt>
            <dd>
              <%= link_to @current_song.album.to_s , album_path(@current_song.album) %>
            </dd>

            <dt>Song</dt>
            <dd>
              <%= link_to song_path(@current_song) , class: 'breakable' do %>
                <%= @current_song.name %>
              <% end %>
            </dd>

            </dd>
            <dt>Duration</dt>
            <dd>
              <%= @current_song.seconds_to_s %> (Now playing <span class='now_playing'></span>)
              <% if @player_state.paused %>
                <strong>PAUSED</strong>
              <% end %>
            </dd>
        <% else %>
          <%# Radio info %>
          <%# Radio image %>
          <div style="float: right">
            <%= render 'artists/artist_image' ,
              { artist: @player_state.radio , span_class: 'img_container' } %>
          </div>
          <dt>Radio</dt>
          <dd>
            <%= link_to @player_state.radio.name, radio_path(@player_state.radio) %>
          </dd>
        <% end %>
      </dl>
    </div>

    <%# Be sure the image does not overflow %>
    <div style="clear:both"></div>

  <% else %>
    <p>Player stopped</p>
  <% end %>
</div>

app/views/player/_player_buttons.html.erb
<%#
  Render player buttons
  PARAMS:
  compact: true to render on the page header. false to render on the player
%>
<%
  compact = false if local_assigns[:compact].nil?
  btn_style = compact ? 'btn btn-default btn-sm' : 'btn btn-default btn-lg'
%>

<%= link_to music_cmd_player_path( { :cmd => :start } ), remote: true ,
  class: btn_style , title: 'Play' do %>
  <span class="glyphicon glyphicon-play"></span>
<% end %>

<%= link_to music_cmd_player_path( { :cmd => :stop } ), remote: true ,
  class: btn_style , title: 'Stop' do %>
  <span class="glyphicon glyphicon-stop"></span>
<% end %>

<% if controller.player_state.mode == PlayerState::SOURCE_FILE_SONGS %>
  <%= link_to music_cmd_player_path( { :cmd => :pause } ), remote: true,
    class: btn_style , id: 'lnk_pause_player' , title: 'Pause' do %>
    <span class="glyphicon glyphicon-pause"></span>
  <% end %>
<% end %>

<%= link_to music_cmd_player_path( { :cmd => :previous } ), remote: true,
  class: btn_style , title: 'Play previous' do %>
  <span class="glyphicon glyphicon-step-backward"></span>
<% end %>

<%= link_to music_cmd_player_path( { :cmd => :next } ), remote: true,
  class: btn_style  , title: 'Play next' do %>
    <span class="glyphicon glyphicon-step-forward"></span>
<% end %>

<% if !controller.player_state.is_streaming? %>
  <%# Button to refresh the player state. Only when playing on speakers %>
  <%= link_to music_cmd_player_path( { :cmd => :refresh } ), remote: true,
    class: btn_style , id: 'lnk_refresh_player',
    title: 'Refresh player state' do %>
    <span class="glyphicon glyphicon-refresh"></span>
  <% end %>
<% end %>

<% if compact %>
  <%# Scroll to top button %>
  <a id="top_link" href="#top" class="<%= btn_style %>" title="Scroll to top">
      <i class="glyphicon glyphicon-chevron-up"></i>
  </a>
<% end %>

app/views/player/index.html.erb
<a id="top"></a>

<p style="text-align: center">

  <%# Play list selector %>
  <%= select_tag "play_lists" ,
    options_from_collection_for_select(@play_lists, :id , :name , @play_list_id ) ,
    class: 'form-control' ,
    autocomplete: "off"
  %><br/>

  <%# Player buttons %>
  <%= render 'player_buttons' %>
</p>

<%# Volume %>
<div>
  <span class="glyphicon glyphicon-volume-up"></span>
  <input id="volumeControl" data-slider-id='volumeSlider' type="text" data-slider-min="0"
    data-slider-max="100" data-slider-step="1" data-slider-value="<%= @player_state.volume %>"
    style="width:100%"/>
</div>

<%# Radio / song information %>
<div class="well">
  <%# This div is entirelly replaced each time the song info is updated %>
  <div id="player">
    <%= render 'player' %>
  </div>
  <% if @player_state.mode == PlayerState::SOURCE_FILE_SONGS %>
    <%# The play slider %>
    <input id="playSlider" data-slider-id='playSliderSlider' type="text" data-slider-min="0"
      data-slider-max="100" data-slider-step="1" data-slider-value="0"
      style="width:100%"/>
  <% end %>
</div>

<%
  puts "***2 #{@player_state.mode.inspect} , #{PlayerState::SOURCE_FILE_SONGS.inspect} , #{@player_state.mode == PlayerState::SOURCE_FILE_SONGS}"
%>

<% if @player_state.mode == PlayerState::SOURCE_FILE_SONGS %>
  <%# Playing files %>

  <% puts "*** Playing files" %>

  <h2><%= @play_list.name %></h2>
  <!-- Reproduction queue filter -->
  <div id="queue_filter_div">
    <%= render 'shared/songs_filter/form' , { id: :queue , :songs_set => @queue_songs } %>
  </div>
  <!-- Reproduction queue operations -->
  <div class="songs_ops_container sticky_ops" id="songs_ops_container">
    <%# Table operations %>
    <%= render 'shared/songs_table/operations' , { add_to_queue: false , show_delete: false } %>
    <a href="#" id="remove_songs_queue" class="btn btn-warning" title="Remove songs from the play list">
      <span class="glyphicon glyphicon-remove"></span>
      <span class="hidden-xs">Remove</span>
    </a>
  </div>
  <!-- Reproduction queue songs table -->
  <div id="queue_table_div">
    <%= render 'shared/songs_table/table' , { id: :queue , songs_set: @queue_songs } %>
  </div>

<% else %>

<% puts "*** Playing radio" %>

  <%# Playing radio %>
  <h2>Radios</h2>
  <%= render 'radios/table' %>
<% end %>

<%# Load the next page of songs %>
<%= hidden_field_tag('load_page' , load_page_player_path ) %>

<%# Path to execute music commands with a get %>
<%= hidden_field_tag('music_cmd_path' , music_cmd_player_path ) %>

<%# Path to execute music commands with a post %>
<%= hidden_field_tag('music_cmd_post_path' , music_cmd_post_player_path ) %>

<%# Path to create a new play list %>
<%= hidden_field_tag('new_play_list_path' , new_play_list_path ) %>

<%# Path to change the play list %>
<%= hidden_field_tag('change_play_list_player_path' , change_play_list_player_path ) %>

<%# Initialize the page %>
<script>
  pageState.setPage(playerPage);
</script>

app/views/player/music_cmd.js.erb
<%#
  Response for the execution of a music command
%>
try {
  <% if @toast %>
    toastr["<%= @toast.status %>"]( "<%= escape_javascript( @toast.info ) %>" );
  <% end %>

  <%# Update small player %>
  $("#small_player")
    .html("<%= escape_javascript( render partial: 'layouts/small_player' ) %>");

  <%# Restart the song timer %>
  if( smallPlayer.songTimer )
    smallPlayer.songTimer.start();

  if( pageState.getPageId() == 'playerPage' ) {

    <%# Update player state %>
    $("#player")
      .html("<%= escape_javascript( render partial: 'player' ) %>");

    <%# Paint the current playing song %>
    playerPage.paintCurrentSong();

    <%# Restart the song timer %>
    if( playerPage.songTimer )
      playerPage.songTimer.start();

    <%# Set the current volume %>
    playerPage.volume.setVolume( <%= @player_state.volume %> );

    <% if @refresh_queue %>
      <%# Refresh the reproduction queue %>
      playerPage.queueFilter.refreshWithData(<%=raw get_filter_changed_response.to_json %>);
    <% end %>

    <%# If somebody else has switched between radio and mp3, refresh the entire
        page %>
    playerPage.checkModeChange();

  }

  <% if @streaming_js_command %>
    <%# Streaming javascript command %>
    <%=raw @streaming_js_command %>
  <% end %>

}
catch(e) {
  console.log(e);
}