config/routes.rb
Rails.application.routes.draw do

  resource :player , only: [ :index ] do
    get 'music_cmd'  => 'player#music_cmd'
    post 'music_cmd_post' => 'player#music_cmd'
    get 'load_page' => 'player#load_page'
    get 'change_play_list' => 'player#change_play_list'
    get 'suggest' => 'player#suggest'
  end

  resources :songs do
    get 'load_page' , on: :collection
    get 'music_cmd', on: :collection
    get  'add_to_queue', on: :collection
    post 'add_to_queue', on: :collection
    get 'edit_multiple', on: :collection
    post 'update_multiple', on: :collection
    get 'download'
    get 'download_multiple', on: :collection
    get 'download_playlist', on: :collection
    post 'delete_multiple', on: :collection
    get 'suggest' , on: :collection
    get 'excel' , on: :collection
  end

  resources :artists , only: [ :index , :edit , :update , :show ] do
    get 'search_wikipedia' , on: :collection
    get 'get_wikipedia_image' , on: :collection
    get 'load_page' , on: :collection
    post 'join'
    get 'suggest' , on: :collection
    post 'add_to_queue', on: :collection
    get 'download_playlist', on: :collection
    get 'download_multiple', on: :collection
  end

  resources :albums , only: [ :index , :show , :edit , :update ] do
    get 'suggest' , on: :collection
    get 'load_page' , on: :collection
    get 'suggest' , on: :collection
    post 'add_to_queue', on: :collection
    get 'download_playlist', on: :collection
    get 'download_multiple', on: :collection
  end

  resources :play_lists

  resources :radios do
    get 'create_spanish_radios', on: :collection
  end

  resources :tasks , only: [ :index , :new , :create ]

  resource :setting , only: [ :edit , :update ] do
    post 'speech'
    get 'recalculate_metadata'
    get 'start_music_service'
    get 'stop_music_service'
    get 'shutdown'
    get 'mount_usb_drive'
  end

  resource :tools , only: [] do
    get 'youtube', on: :collection
    post 'get_youtube', on: :collection
    get 'duplicated_songs', on: :collection
    get 'readme' , on: :collection
  end

  resources :logs , only: [ :index , :show ] do
    get 'load_page' , on: :collection
    post 'clear' , on: :collection
  end

  root 'player#index'

end

app/models/setting.rb
require 'mkmf'

# Stores the application settings
class Setting < ActiveRecord::Base

  # Default music directory
  DEFAULT_MUSIC_DIR_PATH = '/home/toni/Música/grabados'

  # Default speech command line program
  DEFAULT_SPEECH_CMD = 'espeak -ves+f1 $TEXT'

  # Default wikipedia to use
  DEFAULT_WIKIPEDIA = 'en.wikipedia.org'

  # Default initial message
  DEFAULT_INITIAL_MESSAGE = 'Uep! Com anàm!'

  # Default shared folder
  DEFAULT_SHARED_FOLDER = '\\shoesbox\pi compartida\musica'

  # Default selector for spanish wikipedia
  DEFAULT_IMAGE_SELECTOR = 'div#content div#bodyContent table.infobox tr td a.image'

  ###################################################
  # ATTRIBUTES
  ###################################################

  ##
  # :attr_accessor: music_dir_path
  # Absolute path to the directory where the music is stored
  # (length = Constants::NAME_MAX_LENGTH)

  ##
  # :attr_accessor: shared_folder
  # Shared folder UNC path for the music directory path
  # (length = Constants::PATH_MAX_LENGTH)

  ##
  # :attr_accessor: speech_cmd
  # Command line to speech a text on the speakers. If it's empty, the speech
  # will be disabled. It must to contain a text '$TEXT' that will be replaced
  # by the text to speech
  # (length = 60)

  ##
  # :attr_accessor: wikipedia_host
  # Wikipedia host to link music info
  # (length = 100)

  ##
  # :attr_accessor: initial_message
  # Initial speech message to speech when the music server is started
  # (length = 200)

  ##
  # :attr_accessor: image_selector
  # CSS tag selector for artist image on wikipedia pages
  # (length = Contants::URL_MAX_LENGTH)

  ##
  # :attr_accessor: trashcan_folder
  # Folder where to store deleted songs
  # (length = Contants::PATH_MAX_LENGTH)

  ##
  # :attr_accessor: youtube_folder
  # Folder where to store downloaded songs
  # (length = Contants::PATH_MAX_LENGTH)

  ##
  # :attr_accessor: keypad_device
  # Keypad device. If it's empty, there is no keypad
  # (length = Contants::PATH_MAX_LENGTH)
  
  ###################################################
  # VALIDATIONS
  ###################################################

  validates :music_dir_path,
    presence: true ,
    length: { maximum: Constants::PATH_MAX_LENGTH }

  validates :speech_cmd ,
    length: { maximum: 60 }

  validates :wikipedia_host ,
    length: { maximum: 100 }

  validates :initial_message ,
    length: { maximum: 200 }

  validates :trashcan_folder,
    length: { maximum: Constants::PATH_MAX_LENGTH }

  validates :youtube_folder,
    length: { maximum: Constants::PATH_MAX_LENGTH }

  validate  :validate_music_dir_path ,
            :validate_speech_cmd

  ###################################################
  # MEMBERS
  ###################################################

  # Get the application settings.
  # If it does not exists, it will be created with default values
  # [+returns+] The Setting object with the application settings
  def self.get_settings
    settings = Setting.take
    if !settings
      # Create default settings
      settings = Setting.new
      settings.music_dir_path = DEFAULT_MUSIC_DIR_PATH
      settings.speech_cmd = DEFAULT_SPEECH_CMD
      settings.wikipedia_host = DEFAULT_WIKIPEDIA
      settings.shared_folder = DEFAULT_SHARED_FOLDER
      settings.initial_message = DEFAULT_INITIAL_MESSAGE
      settings.image_selector = DEFAULT_IMAGE_SELECTOR

      # Do not validate: Default values may be wrong for this computer
      settings.save(validate: false)
    end
    return settings
  end

  # Validates the music_dir_path property
  def validate_music_dir_path
    if !Dir.exists? self.music_dir_path
      errors.add( :music_dir_path , "#{self.music_dir_path} does not exist")
    end
  end

  # Validates the speech_cmd property
  def validate_speech_cmd

    # Empty value is OK
    if self.speech_cmd
      self.speech_cmd = self.speech_cmd.strip
    else
      return
    end
    return if self.speech_cmd.empty?

    array = prepare_speech_cmd(nil)

    if !find_executable array[0]
      errors.add( :speech_cmd , "#{array[0]} does not exist or it's " +
        "not on the path. It's safe to left this field empty")
    end

    if !self.speech_cmd.include? '$TEXT'
      errors.add( :speech_cmd , "#{self.speech_cmd} does not contains " +
        '$TEXT. This  will be replaced by the text to speech')
    end

  end

  # Get an Array with the command line to speech some text
  # [+text+] Text to speech. If it's nill, the text $TEXT will not be replaced
  # [+returns+] Array with the command line splitted. nil if there was
  # no speech program configured
  def prepare_speech_cmd(text)
    return nil if self.speech_cmd.empty?
    array = self.speech_cmd.split(' ')
    array = array.map{ |x| x.gsub('$TEXT' , text) } if text
    return array
  end

  # Get the shared path of a relative path
  # [+path+] relative path to convert to shared folder
  # [+returns+] the path inside self.shared_folder
  def shared_path(path)
    result = self.shared_folder
    result += '\\' if !result.ends_with?('\\')
    result += path.gsub('/' , '\\')
    return result
  end

  # Get the relative path of a file to the music directory
  # [+file_path+] The absolute file path
  # [+returns+] The relative path
  def relative_path_from_absolute(file_path)
    base_path = Pathname.new(self.music_dir_path)
    file_path = Pathname.new(file_path)
    return file_path.relative_path_from( base_path ).to_s
  end

  # Get the trashcan folder path with a trailing separator ('/')
  def trashcan_folder_normalized
    folder = self.trashcan_folder
    folder += '/' if !folder.end_with?('/')
    return folder
  end

end

app/controllers/settings_controller.rb
load "#{Rails.root}/lib/music/client.rb"
load "#{Rails.root}/lib/music/cmd_result.rb"

# Application settings controller
class SettingsController < MusicBaseController

  # Edit form
  def edit
    @setting = Setting.get_settings
    render_edit
  end

  # Update settings on db
  def update

    ok = true
    # Save settings
    @setting = Setting.get_settings
    if @setting.update(settings_params)
      # Notify to the music server the settings change
      execute_music_cmd_check_error(@setting.errors , :reload_settings)
    end

    if @setting.errors.any?
      render_edit
    else
      redirect_to root_path
    end

  end

  # Speech form
  def speech
    @setting = Setting.get_settings
    @speech_errors = ActiveModel::Errors.new(self)
    execute_music_cmd_check_error( @speech_errors , :speech , { message: params[:speech_text] } )
    render_edit
  end

  # Clean and recalculate metadata action
  def recalculate_metadata
    @setting = Setting.get_settings
    @result = execute_music_cmd( :search_meta , { clean: true } )
    render 'command_result'
  end

  # Start the music service action
  def start_music_service
    execute_system_cmd('/etc/init.d/music_daemon start')
  end

  # Stop the music service action
  def stop_music_service
    execute_system_cmd('/etc/init.d/music_daemon stop')
  end

  # Shutdown the device action
  def shutdown
    execute_system_cmd('shutdown -h now')
  end

  # Mount my usb drive (ugly hack, i know)
  def mount_usb_drive
    execute_system_cmd('mount /home/pi/compartida/musica/discousb')
  end

  ################################################################
  protected
  ################################################################

  # Render the form in edit mode
  def render_edit
    @txt_disk_usage = `df`
    @txt_memory_usage = `free -m`

    # Get temperature
    begin
      @temperature = `cat /sys/class/thermal/thermal_zone0/temp`
      @temperature = @temperature.to_i / 1000.0
      @temperature = "#{@temperature} Cº"
    rescue
      Log.log_last_exception
      @temperature = '??? Cº'
    end

    # Available input devices:
    begin
      devs_dir = '/dev/input/by-id'
      if Dir.exists?(devs_dir)
        @input_devices = Dir
          .entries( devs_dir )
          .select { |d| !File.directory?(d) }
      else
        @input_devices = []
      end
    rescue
      Log.log_last_exception
      @input_devices = []
    end

    render 'edit'
  end

  def execute_system_cmd(cmd)
    result_text = `#{cmd} 2>&1`
    puts result_text
    result_text = "Ok" if result_text.empty? && $?.success?
    @result = CmdResult.new( $?.success? ? :success : :error , result_text )
    if !$?.success?
      Log.log_error("Error executing #{cmd}", result_text)
    end
    puts @result.inspect
    render 'command_result'
  end

  # Execute a command on the music server
  # [+errors+] Errors list where store errors messages
  # [+cmd+] Command to send
  # [+cmd_params+] Command parameters to send
  def execute_music_cmd_check_error(errors, cmd, cmd_params = {})
    result = execute_music_cmd(cmd, cmd_params)
    if result.status == :error
      errors.add( :base , 'Music server error: ' + result.info )
    end
    return errors.count == 0
  end

  # Get the form parameters
  def settings_params
    params.require(:setting).permit(
      :music_dir_path, :speech_cmd, :wikipedia_host , :initial_message ,
      :shared_folder , :image_selector , :trashcan_folder , :youtube_folder ,
      :keypad_device
    )
  end

end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/command_result.js.erb
try {
  toastr["<%= @result.status %>"]( "<%= escape_javascript( @result.info ) %>" );
}
catch(e) {
  console.log(e);
}

app/views/settings/edit.html.erb
<% content_for :title, 'Settings' %>
<h1>Settings</h1>

<%= render 'shared/form_messages' , { messages: @setting.errors } %>

<%= form_for @setting do |f| %>
  <div class="form-group">
    <%= f.label :music_dir_path , class: 'control-label' %><br>
    <%= f.text_field :music_dir_path , class: 'form-control' ,
      maxlength: Constants::PATH_MAX_LENGTH ,
      placeholder: 'Directory where music is stored'%>
  </div>

  <div class="form-group">
    <%= f.label :trashcan_folder , 'Music trashcan folder' , class: 'control-label' %><br>
    <%= f.text_field :trashcan_folder , class: 'form-control' ,
    maxlength: Constants::PATH_MAX_LENGTH ,
    placeholder: 'Directory where deleted song files are moved' %>
  </div>

  <div class="form-group">
    <%= f.label :youtube_folder , 'Youtube downloaded songs destination' , class: 'control-label' %><br>
    <%= f.text_field :youtube_folder , class: 'form-control' , maxlength: 100 %>
  </div>

  <div class="form-group">
    <%= f.label :shared_folder , class: 'control-label' %><br>
    <%= f.text_field :shared_folder , class: 'form-control' ,
    maxlength: Constants::PATH_MAX_LENGTH ,
    placeholder: 'UNC path of the shared folder where music is stored'%>
  </div>

  <div class="form-group">
    <%= f.label :speech_cmd , class: 'control-label' %><br>
    <%= f.text_field :speech_cmd , class: 'form-control' , maxlength: 60,
    placeholder: 'Command line to speach text. $TEXT is replaced by the text to speach' %>
  </div>

  <div class="form-group">
    <%= f.label :initial_message , class: 'control-label' %><br>
    <%= f.text_field :initial_message , class: 'form-control' , maxlength: 200 ,
    placeholder: 'Text to speach when player is started (ex. "Hello")' %>
  </div>

  <div class="form-group">
    <%= f.label :wikipedia_host , class: 'control-label' %><br>
    <%= f.text_field :wikipedia_host , class: 'form-control' , maxlength: 100 ,
    placeholder: 'Wikipedia host name (ex. es.Wikipedia.org)'%>
  </div>

  <div class="form-group">
    <%= f.label :image_selector , 'Wikipedia artist image selector' , class: 'control-label' %><br>
    <%= f.text_field :image_selector , class: 'form-control' , maxlength: 100,
    placeholder: 'CSS selector for artist image in wikipedia pages' %>
  </div>

  <div class="form-group">
    <%= f.label :keypad_device , class: 'control-label' %>
    <div class="input-group">
      <%= f.text_field :keypad_device , class: 'form-control' ,
        placeholder: 'Keypad device (ex. "/dev/input/by-id/usb-05a4_USB_Compliant_Keypad-event-kbd")'%>
      <div class="input-group-btn">
        <button type="button" class="btn btn-default dropdown-toggle"
          data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span class="caret"></span>
        </button>
        <ul class="dropdown-menu dropdown-menu-right">
          <% @input_devices.each do |d| %>
            <li><a href="#" class="keypad_link"><%= d %></a></li>
          <% end %>
        </ul>
      </div><!-- /btn-group -->
    </div><!-- /input-group -->
  </div>

  <%= f.submit 'Save' , class: 'btn btn-primary' %>
<% end %>

<h3>Speech</h3>
<%= render 'shared/form_messages' , { messages: @speech_errors } %>
<%= form_tag speech_setting_path do |f| %>

  <div class="form-group">
    <%= label_tag :speech_text , 'Text to speech' , class: 'control-label' %><br>
    <%= text_field_tag :speech_text , '' , class: 'form-control',
      placeholder: 'Texto to speech (ex. "Hello")'%>
  </div>

  <%= submit_tag 'Speech' , class: 'btn btn-primary' %>
<% end %>

<h3>Tools</h3>
<p>
  <%= link_to recalculate_metadata_setting_path , remote: true, type: 'script',
    data: { confirm: 'Are you sure you want to clean meta info and recalculate it' } ,
    class: 'btn btn-warning' do %>
    <span class="glyphicon glyphicon-search"></span> Recalculate wikipedia links
  <% end %>

  <%= link_to start_music_service_setting_path , remote: true , type: 'script',
    class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-play"></span> Start music service
  <% end %>

  <%= link_to stop_music_service_setting_path , remote: true , type: 'script',
    class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-stop"></span> Stop music service
  <% end %>

  <%= link_to shutdown_setting_path , remote: true , type: 'script',
    data: { confirm: 'Are you sure you want to shutdown the device?' } ,
    class: 'btn btn-danger' do %>
    <span class="glyphicon glyphicon-off"></span> Shutdown the device
  <% end %>

  <%= link_to mount_usb_drive_setting_path , remote: true , type: 'script',
    class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-import"></span> Mount /home/pi/compartida/musica/discousb
  <% end %>

  <%= link_to music_cmd_songs_path({ :cmd => :clean_db }) ,
    data: { confirm: 'Are you sure you want to clean the songs database?' },
    class:'btn btn-danger',
    remote: true,
    type: 'script' do %>
    <span class="glyphicon glyphicon-refresh"></span> Rebuild songs database
  <% end %>
  
</p>

<h3>Disk and memory usage</h3>
<pre>
<%= @txt_disk_usage %>
</pre>
<pre>
<%= @txt_memory_usage %>
</pre>
<pre>
CPU temperature: <%= @temperature %>
</pre>

<%# Initialize the page %>
<%= javascript_tag do %>
  pageState.setPage(settingsEditPage);
<% end %>