config/routes.rb
Rails.application.routes.draw do

  resource :player , only: [ :index ] do
    get 'music_cmd'  => 'player#music_cmd'
    post 'music_cmd_post' => 'player#music_cmd'
    get 'load_page' => 'player#load_page'
    get 'change_play_list' => 'player#change_play_list'
    get 'suggest' => 'player#suggest'
  end

  resources :songs do
    get 'load_page' , on: :collection
    get 'music_cmd', on: :collection
    get  'add_to_queue', on: :collection
    post 'add_to_queue', on: :collection
    get 'edit_multiple', on: :collection
    post 'update_multiple', on: :collection
    get 'download'
    get 'download_multiple', on: :collection
    get 'download_playlist', on: :collection
    post 'delete_multiple', on: :collection
    get 'suggest' , on: :collection
    get 'excel' , on: :collection
  end

  resources :artists , only: [ :index , :edit , :update , :show ] do
    get 'search_wikipedia' , on: :collection
    get 'get_wikipedia_image' , on: :collection
    get 'load_page' , on: :collection
    post 'join'
    get 'suggest' , on: :collection
    post 'add_to_queue', on: :collection
    get 'download_playlist', on: :collection
    get 'download_multiple', on: :collection
  end

  resources :albums , only: [ :index , :show , :edit , :update ] do
    get 'suggest' , on: :collection
    get 'load_page' , on: :collection
    get 'suggest' , on: :collection
    post 'add_to_queue', on: :collection
    get 'download_playlist', on: :collection
    get 'download_multiple', on: :collection
  end

  resources :play_lists

  resources :radios do
    get 'create_spanish_radios', on: :collection
  end

  resources :tasks , only: [ :index , :new , :create ]

  resource :setting , only: [ :edit , :update ] do
    post 'speech'
    get 'recalculate_metadata'
    get 'start_music_service'
    get 'stop_music_service'
    get 'shutdown'
    get 'mount_usb_drive'
  end

  resource :tools , only: [] do
    get 'youtube', on: :collection
    post 'get_youtube', on: :collection
    get 'duplicated_songs', on: :collection
    get 'readme' , on: :collection
  end

  resources :logs , only: [ :index , :show ] do
    get 'load_page' , on: :collection
    post 'clear' , on: :collection
  end

  root 'player#index'

end

app/models/album.rb
# An album with songs (active record model)
class Album < ActiveRecord::Base

  ## Name for the unknown album
  UNKNOWN_ALBUM_NAME = "Unknown album"

  ###################################################
  # ATTRIBUTES
  ###################################################

  ##
  # :attr_accessor: name
  # Album name (length = Constants::NAME_MAX_LENGTH)

  ##
  # :attr_accessor: year
  # Album year. N(4)

  ###################################################
  # RELATIONS
  ###################################################

  ##
  # :attr_accessor: artist
  # Artist owner of the song
  #belongs_to :artist

  ##
  # :attr_accessor: songs
  # Relation of the album Songs
  has_many :songs

  ###################################################
  # VALIDATIONS
  ###################################################

  validates :name, presence: true , length: { maximum: Constants::NAME_MAX_LENGTH }

  ###################################################
  # MEMBERS
  ###################################################

  ##
  # Returns an String description of the album
  def to_s
    txt = name
    txt += " (#{self.year})" if self.year && self.year > 0
    return txt
  end

  # Updates the artist and album data  on the associated mp3 files to this album
  # [+settings+] The application Setting
  def update_mp3_files(settings)
    songs.each do |song|
      song.update_file(settings)
    end
  end

  # Normalize an Album name
  # [+album_name+] The album name
  # [+returns+] The normalized album name
  def self.normalize_name(album_name)
    album_name = UNKNOWN_ALBUM_NAME if !album_name
    album_name.strip!
    album_name = UNKNOWN_ALBUM_NAME if album_name.empty?
    return album_name
  end

end

app/models/song.rb
# taglib-ruby gem (gem install taglib-ruby)
require 'taglib'

# Song information (active record model)
class Song < ActiveRecord::Base

  ###################################################
  # ATTRIBUTES
  ###################################################

  ##
  # :attr_accessor: name
  # Song name (length = Constants::NAME_MAX_LENGTH)

  ##
  # :attr_accessor: path
  # Song path (length = Constants::PATH_MAX_LENGTH).
  # The path is relative to the root path of the music directory

  ##
  # :attr_accessor: genre
  # Description of the song genre (length = Constants::NAME_MAX_LENGTH).

  ##
  # :attr_accessor: seconds
  # Lenght of the song, in seconds. N(9)

  ##
  # :attr_accessor: track
  # Number of order of the song inside the owner Album. N(9)

  ##
  # :attr_accessor: bitrate
  # bit rate in kb/s (kilobit per second). N(5)

  ##
  # :attr_accessor: channels
  # Number of channels. N(1)

  ##
  # :attr_accessor: sample_rate
  # sample rate in Hz. N(6)

  ##
  # :attr_accessor: file_size
  # file size, in bytes. N(12)

  ###################################################
  # RELATIONS
  ###################################################

  ##
  # :attr_accessor: album
  # Owner Album
  belongs_to :album

  ##
  # :attr_accessor: artist
  # Owner Artist
  belongs_to :artist

  ##
  # :attr_accessor: play_list_songs
  # Relation of PlayListSong that reference to this song
  has_many :play_list_songs , dependent: :delete_all

  ###################################################
  # VALIDATIONS
  ###################################################

  validates :name, presence: true , length: { maximum: Constants::NAME_MAX_LENGTH }

  ###################################################
  # MEMBERS
  ###################################################

  # Returns the directory name of the song, relative to the music directory
  def dirname
    return File.dirname( self.path )
  end

  # Fill the song info from a audio file tags
  # [+path+] Song path, relative to the root music directory
  # [+file_tags+] File tags, type TagLib::File (http://www.rubydoc.info/gems/taglib-ruby/TagLib)
  # [+file_size+] The file size, in bytes
  def fill( path , file , file_size )

    # File info
    self.path = path
    self.file_size = file_size

    # Set default values:
    self.name = ''
    self.genre = ''
    self.seconds = 0
    self.track = 0
    self.bitrate = 0
    self.channels = 0
    self.sample_rate = 0

    # Get file tags
    file_tags = file.tag
    if file_tags
      self.name = file_tags.title if file_tags.title
      self.genre = file_tags.genre if file_tags.genre
      self.track = file_tags.track if file_tags.track
    end

    # Be sure we have a name
    if self.name.empty?
      self.name = File.basename(path, ".*")
      self.name.gsub!('_',' ')
    end
    self.name.strip!

    # Try to extract the track number from the name
    begin
      if self.track == 0 && self.name =~ /\A\d+.*/
        # Get the initial number:
        self.track = self.name[/\A\d+/].to_i
        self.track = 0 if self.track < 0 || self.track > 9999
      end
    rescue
    end

    # Cut long names
    if self.name.length > Constants::NAME_MAX_LENGTH
      self.name = self.name[0..(Constants::NAME_MAX_LENGTH-1)]
    end
    if self.genre && self.genre.length > Constants::NAME_MAX_LENGTH
      self.genre = self.genre[0..(Constants::NAME_MAX_LENGTH-1)]
    end

    # Get audio properties
    audio_props = file.audio_properties
    if audio_props
      self.seconds = audio_props.length if audio_props.length
      self.bitrate = audio_props.bitrate if audio_props.bitrate
      self.channels = audio_props.channels if audio_props.channels
      self.sample_rate = audio_props.sample_rate if audio_props.sample_rate
    end

  end

  # Returns the song description
  def to_s(show_id = false)
    s = ''
    s += self.track.to_s + ". " if self.track && self.track > 0
    s += self.name ? self.name : "Unknown song name"
    s += " / " + self.album.to_s
    s += " / " + self.artist.to_s
    s += " (#{self.id})" if show_id
    return s
  end

  # Returns a String with the song length formatted
  def seconds_to_s
    return Song.format_seconds_to_s(self.seconds)
  end

  # Returns the absolute path of the song file
  # [+settings+] The Setting with the base music directory
  def full_path(settings)
    return File.join( settings.music_dir_path , self.path )
  end

  # Update the meta tags on the mp3 file
  # [+settings+] The application Setting
  def update_file(settings)
    file_path = self.full_path(settings)
    TagLib::MPEG::File.open(file_path) do |file|
      file.tag.artist = self.artist.name
      file.tag.album =  self.album.name
      file.tag.year = self.album.year ? self.album.year : 0
      file.tag.genre = self.genre
      file.tag.title = self.name
      file.save
    end
  end

  # Returns a String with a number of seconds formatted
  # [+seconds+] Integer with the number of seconds
  # [+returns+] String with the seconds formated as mm:ss
  def self.format_seconds_to_s(seconds)
    minutes = seconds / 60
    seconds_rest = seconds % 60
    return "#{minutes}:#{sprintf '%02d', seconds_rest}"
  end

end

app/controllers/songs_controller.rb
require 'tempfile'
require 'csv'
load "#{Rails.root}/lib/music/client.rb"

# Work with available songs controller
class SongsController < MusicBaseController

  # Suggest names on searches
  include SuggestModule

  # Support zip download
  include ZipSongsModule

  # Maximum number of songs to delete at the same time
  MAX_DOWNLOAD_DELETE = 100

  ###################################################
  # Actions
  ###################################################

  # Songs list
  def index
    @songs_count = Song.count
    load_songs
  end

  # Show the song
  def show
    render_show
  end

  # Edit a song
  def edit
    params[:songid] = []
    params[:songid] << params[:id]
    edit_multiple
    render'edit_multiple'
  end

  # Edit multiple songs
  def edit_multiple

    # Get songs to edit
    ids = get_selected_song_ids
    if ids.length > 100
      @errors = ActiveModel::Errors.new(self)
      @errors.add(:base , 'Maximum number of song to edit at same time is 100')
      ids = ids.take(100)
    end
    @songs = Song.find( ids )

    # Check what to update:
    if @songs.group_by{ |s| s.artist.id }.keys.length == 1
      @update_artist = true
      @artist_name = @songs[0].artist.name
    else
      @update_artist = false
      @artist_name = 'Various'
    end

    if @songs.group_by{ |s| s.album.id }.keys.length == 1
      @update_album = true
      @album_name = @songs[0].album.name
    else
      @update_album = false
      @album_name = 'Various'
    end

    if @songs.group_by{ |s| s.genre }.keys.length == 1
      @update_genre = true
      @genre = @songs[0].genre
    else
      @update_genre = false
      @genre = 'Various'
    end

  end

  # Update multiple songs
  def update_multiple

    songs_ids = params[:songs].keys.map { |k| k.to_i }
    editor = SongsEditor.new( songs_ids )

    # Do common changes
    editor.set_artist_name( params[:artist] ) if params[:update_artist]
    editor.set_album_name( params[:album] ) if params[:update_album]
    editor.set_genre( params[:genre] ) if params[:update_genre]

    # Do each song change
    editor.songs.each do |song|
      song_params = params[:songs][ song.id.to_s ]
      song.track = song_params[:track]
      song.name = song_params[:name]
    end

    # Save changes and purge albums / artists
    settings = Setting.get_settings
    editor.save_changes(settings)
    editor.purge_old_artists_albums

    if !editor.with_errors?

      # Fire the metadata search
      execute_music_cmd( :search_meta )

      if editor.songs.count == 1
        redirect_to song_path( editor.songs[0] )
      else
        redirect_to songs_path
      end
    else
      # TODO: Render errors
      render 'edit_multiple'
    end

  end

  # Load next songs page
  def load_page
    load_songs
    load_page_template(@songs)
  end

  # Executes a command on the music server
  def music_cmd
    result = execute_music_cmd_from_parms
    # Feedback the user
    if result
      result.info = "OK" if !result.info
      @toast = result
    end
    load_songs
    render 'music_cmd'
  end

  # Download one song action
  def download

    # Song info
    song = Song.find(params[:song_id])
    settings = Setting.get_settings

    # Default range to download (all the file)
    file_begin = 0
    file_end = song.file_size - 1

    # Get the range to download from the request
    if !request.headers["Range"]
      # Download the entire file
      status_code = "200 OK"
    else
      # Download a range
      puts "*** Request header: #{request.headers["Range"]}"
      status_code = "206 Partial Content"
      match = request.headers['range'].match(/bytes=(\d+)-(\d*)/)
      if match
        file_begin = match[1]
        file_end = match[2] if match[2] && !match[2].empty?
        puts "*** Requesting file range[#{file_begin.to_s}-#{file_end.to_s}]"
      end
      response.header["Content-Range"] = "bytes " + file_begin.to_s + "-" +
        file_end.to_s + "/" + song.file_size.to_s
    end

    # Common headers
    #response.header["Last-Modified"] = @media.file_updated_at.to_s < NOT AVAILABLE
    response.header["Cache-Control"] = "public, must-revalidate, max-age=0"
    response.header["Pragma"] = "no-cache"
    response.header["Accept-Ranges"]=  "bytes"
    response.header["Content-Transfer-Encoding"] = "binary"

    # File range to download
    offset = file_begin.to_i
    content_length = file_end.to_i - offset + 1
    response.header["Content-Length"] = content_length.to_s

    # Read the requested bytes range:
    song_path = song.full_path(settings)
    partial_content = IO.binread(song_path, content_length, offset)

    # Send the range
    send_data partial_content,
      :filename => File.basename(song.path),
      :type => 'audio/mpeg',
      #:disposition => "inline",
      :stream => true,
      :status => status_code

  end

  # Action to delete multiple songs
  def delete_multiple

    begin
      # Do the deletion
      ids = get_selected_song_ids
      if ids.length > MAX_DOWNLOAD_DELETE
        raise "Maximum number of songs to delete is #{MAX_DOWNLOAD_DELETE}"
      end
      @toast = execute_music_cmd( :delete_songs , { songs_ids: ids } )
      # Refresh the displayed songs
      load_songs
    rescue
      Log.log_last_exception
      @toast = CmdResult.new( :error , $!.message )
    end

    # Render to the response
    render 'music_cmd'

  end

  # Action to delete a song
  def destroy
    result = execute_music_cmd( :delete_songs , { songs_ids: [ params[:id].to_i ] } )
    if result.status == :success
      redirect_to songs_path
    else
      render_show(result)
    end
  end

  # Action to suggest names on the filter
  def suggest
    suggest_classes( [ Song , Artist , Album ] )
  end

  # Action to download the selected songs as an Excel file
  def excel

    excel_songs = get_songs_search_from_params
    excel_songs.select_extra_columns = true
    excel_songs = excel_songs.songs_found.map { |s|
      [ s[SongsSearch::IDX_ARTIST_NAME] , s[SongsSearch::IDX_ALBUM_NAME] ,
        s[SongsSearch::IDX_TRACK] , s[SongsSearch::IDX_SONG_NAME] ,
        s[SongsSearch::IDX_SONG_PATH] , s[SongsSearch::IDX_SONG_LENGTH] ,
        s[SongsSearch::IDX_GENRE] , s[SongsSearch::IDX_BITRATE] ,
        s[SongsSearch::IDX_FILE_SIZE] ]
    }

    respond_to do |format|
      format.html
      format.csv do
        csv = CSV.generate do |csv|
          csv << [ "Artist", "Album", 'Track Number' , "Song" , "Path" ,
            "Length (Seconds)" , "Genre" , "Bitrate (Kb/s)" , "Size (bytes)" ]
          excel_songs.each do |s|
            # Check if the track number is empty:
            s[2] = nil if s[2] == 0
            csv << s
          end
        end
        send_data csv, type: 'text/csv', filename: 'songs.csv'
      end
    end

  end

  ###################################################
  protected
  ###################################################

  def render_show(result = nil)
    @settings = Setting.get_settings
    @song = Song.find(params[:id])
    if result != nil
      @errors = ActiveModel::Errors.new(@song)
      @errors.add(:base, result.info)
    end
    render 'show'
  end

  def get_filter_changed_response
    get_filter_changed_response_base(load_songs, :queue)
  end
  helper_method :get_filter_changed_response

  # Loads and it returns the current songs page
  def load_songs

    return @songs if @songs

    # Get the filter to apply
    filter_parms = ( params[:filter] ? params[:filter] : params )

    @songs = SongsSearch.new
    @songs.apply_filter(filter_parms)
    @songs.page_size = 100
    @songs.page_index = params[:page_index].to_i if params[:page_index]

    return @songs
  end

end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/songs/edit_multiple.html.erb
<% content_for :title, 'Edit songs' %>
<h1>Edit songs</h1>

<%= render 'shared/form_messages' , { messages: @errors } %>

<%= form_tag update_multiple_songs_path do %>

  <h2>General</h2>
  <div class="form-group">
    <%= label_tag :artist , 'Artist' , class: 'control-label' %>
    <div class="checkbox">
      <label>
        <%= check_box_tag 'update_artist' , '1' , @update_artist %>
        Update
      </label>
    </div>
    <%= text_field_tag :artist , @artist_name , class: 'form-control' ,
      maxlength: Constants::NAME_MAX_LENGTH %>
  </div>

  <div class="form-group">
    <%= label_tag :album , 'Album' , class: 'control-label' %>
    <div class="checkbox">
      <label>
        <%= check_box_tag 'update_album' , '1' , @update_album %>
        Update
      </label>
    </div>
    <%= text_field_tag :album , @album_name , class: 'form-control' ,
      maxlength: Constants::NAME_MAX_LENGTH %>
  </div>

  <div class="form-group">
    <%= label_tag :genre , 'Genre' , class: 'control-label' %>
    <div class="checkbox">
      <label>
        <%= check_box_tag 'update_genre' , '1' , @update_genre %>
        Update
      </label>
    </div>
    <%= text_field_tag :genre , @genre , class: 'form-control' ,
      maxlength: Constants::NAME_MAX_LENGTH %>
  </div>

  <h2>Songs information</h2>
  <p>
    <a class="btn btn-default" id="assign_fields">
      <span class="glyphicon glyphicon-tags"></span>
      Try to assing fields from file names
    </a>
  </p>
  <table class="table" id="songs_table">

    <thead>
      <tr>
        <th>Track</th>
        <th>Name</th>
        <th><%# Operations %></th>
      </tr>
    </thead>

    <tbody>
      <% @songs.each do |song| %>
        <%= fields_for "songs[]", song do |f| %>
          <tr>
            <td colspan="2" style="padding-bottom:0; ; border-top: none">
              <label style="margin-bottom: 0">
                <%= song.path %>
              </label>
              <%= render 'shared/form_messages' , { messages: song.errors } %>
            </td>
          </tr>
          <tr>
            <td style="border-top: none">
              <%= f.number_field :track , class: 'form-control', style: 'width: 80px' %>
            </td>
            <td style="border-top: none; width: 100%">
              <%= f.text_field :name , class: 'form-control' %>
            </td>
            <td style="border-top: none;" >
              <%= link_to music_cmd_player_path( song_id: song.id , cmd: 'play_song' ) ,
                remote: true, class:'btn btn-default' do %>
                <span class="glyphicon glyphicon-play"></span>
              <% end %>
          </tr>
        <% end %>
      <% end %>
    </tbody>

  </table>

  <%= submit_tag 'Update songs' , class: 'btn btn-primary' %>

<% end %>

<%# Paths to suggest artists and albums names %>
<%= hidden_field_tag('suggest_artists_path' , suggest_artists_path ) %>
<%= hidden_field_tag('suggest_albums_path' , suggest_albums_path ) %>

<%# Initialize the page %>
<%= javascript_tag do %>
  pageState.setPage(songEditPage);
<% end %>

app/views/songs/index.html.erb
<% content_for :title, 'Songs' %>
<h1>Songs (<%= @songs_count %>)</h1>

<%# General operations %>
<p>

  <% playlist_name = controller.current_player_state.play_list.name %>
  <%= link_to music_cmd_songs_path({ :cmd => :queue_all_and_shuffle }) ,
    data: { confirm: 'Are you sure you want to clean the queue and play all available songs shuffled?' },
    class:'btn btn-default',
    remote: true,
    title: 'Clear the play list, add all songs sorted ramdomly and start to play',
    type: 'script' do %>
    <span class="glyphicon glyphicon-play"></span>
    Play all random on '<%= playlist_name %>'
  <% end %>

  <%= link_to music_cmd_songs_path({ :cmd => :rescan_music }) ,
    class:'btn btn-default',
    remote: true,
    title: 'Check device for songs changes. This can take some time',
    type: 'script' do %>
    <span class="glyphicon glyphicon-refresh"></span> Refresh available songs
  <% end %>

</p>

<%# The filter %>
<%= render 'shared/songs_filter/form' , { id: 'songs' , songs_set: @songs , search_text: params[:text] } %>

<%# Table operations %>
<div class="songs_ops_container sticky_ops">
  <%= render 'shared/songs_table/operations' %>
</div>

<%# Songs table %>
<%= render 'shared/songs_table/table' , { id: 'songs' , songs_set: @songs } %>

<%# Path to load the next songs page %>
<%= hidden_field_tag 'load_page_path' , load_page_songs_path %>

<%# Initialize the page %>
<%= javascript_tag do %>
  pageState.setPage( songsIndexPage );
<% end %>

app/views/songs/music_cmd.js.erb
try {
  <% if @toast %>
    <%# Display a toast with a message %>
    toastr["<%= @toast.status %>"]( "<%= escape_javascript( @toast.info ) %>" );
  <% end %>

  <% if @songs %>
    <%# Refresh the filter and songs table %>
    var songs_table_data = <%=raw get_filter_changed_response.to_json %>;

    if( songsIndexPage.songsFilter )
      songsIndexPage.songsFilter.refreshWithData(songs_table_data);
    else if( playerPage.queueFilter )
      playerPage.queueFilter.refreshWithData(songs_table_data);
  <% end %>

  <% if @streaming_js_command %>
    <%# Streaming javascript command %>
    <%=raw @streaming_js_command %>
  <% end %>
  
}
catch(e) {
  console.log(e);
}

app/views/songs/show.html.erb
<% content_for :title, @song.name %>
<h1><%= @song.name %></h1>

<%= render 'shared/form_messages' , { messages: @errors } %>

<p style="text-align: center">
  <%# Artist image %>
  <%= render 'artists/artist_image' , { artist: @song.artist , size: :thumb ,
    img_class: 'img_100' } %><br />
</p>

<%# Stream player %>
<!-- <audio src="<%= song_download_path( @song ) %>" controls style="margin-top: 10px; width: 100%" >
</audio> -->

<dl>
  <dt>Artist</dt>
  <dd>
    <%= link_to @song.artist.name , artist_path(@song.artist)  %>
  </dd>

  <dt>Album</dt>
  <dd>
    <%= link_to @song.album.to_s , album_path(@song.album) %>
  </dd>

  <% if @song.track > 0 %>
    <dt>Track number</dt>
    <dd>
      <%= @song.track %>
    </dd>
  <% end %>

  <dt>Path</dt>
  <dd>
    <span class="breakable"><%= @settings.shared_path( @song.path ) %></span>
  </dd>

  <% if @song.genre %>
    <dt>Genre</dt>
    <dd>
      <%= @song.genre %>
    </dd>
  <% end %>

  <dt>Length</dt>
  <dd>
    <%= @song.seconds_to_s %>
  </dd>

  <dt>Bit rate</dt>
  <dd>
    <%= @song.bitrate %> Kbits / second
  </dd>

  <dt>Chanels</dt>
  <dd>
    <%= @song.channels %>
  </dd>

  <dt>Sample rate</dt>
  <dd>
    <%= @song.sample_rate %> Hz
  </dd>

  <dt>File size</dt>
  <dd>
    <%= number_to_human_size(@song.file_size) %> (<%= @song.file_size %> bytes)
  </dd>

</dl>

<% playlist_name = controller.current_player_state.play_list.name %>
<%= link_to music_cmd_player_path( song_id: @song.id , cmd: 'play_song' ) ,
  remote: true, class:'btn btn-default' do %>
  <span class="glyphicon glyphicon-play"></span>
  <span class="hidden-xs">Add to '<%= playlist_name %>' and play</span>
<% end %>

<%= link_to add_to_queue_songs_path( song_ids: [ @song.id ] ) ,
  remote: true, class:'btn btn-default' do %>
  <span class="glyphicon glyphicon-plus"></span>
  <span class="hidden-xs">Add to '<%= playlist_name %>'</span>
<% end %>

<%= link_to song_download_path( @song ) ,
  class:'btn btn-default' do %>
  <span class="glyphicon glyphicon-download"></span>
  <span class="hidden-xs">Download</span>
<% end %>

<%= link_to edit_song_path(@song) , class:'btn btn-default' do %>
  <span class="glyphicon glyphicon-edit"></span>
  <span class="hidden-xs">Edit</span>
<% end %>

<%= link_to @song , method: :delete ,
  data: { confirm: 'Are you sure you want to delete the song?' },
  class:'btn btn-danger' do %>
  <span class="glyphicon glyphicon-trash"></span>
  <span class="hidden-xs">Delete</span>
<% end %>