config/routes.rb
Rails.application.routes.draw do

  resource :player , only: [ :index ] do
    get 'music_cmd'  => 'player#music_cmd'
    post 'music_cmd_post' => 'player#music_cmd'
    get 'load_page' => 'player#load_page'
    get 'change_play_list' => 'player#change_play_list'
    get 'suggest' => 'player#suggest'
  end

  resources :songs do
    get 'load_page' , on: :collection
    get 'music_cmd', on: :collection
    get  'add_to_queue', on: :collection
    post 'add_to_queue', on: :collection
    get 'edit_multiple', on: :collection
    post 'update_multiple', on: :collection
    get 'download'
    get 'download_multiple', on: :collection
    get 'download_playlist', on: :collection
    post 'delete_multiple', on: :collection
    get 'suggest' , on: :collection
    get 'excel' , on: :collection
  end

  resources :artists , only: [ :index , :edit , :update , :show ] do
    get 'search_wikipedia' , on: :collection
    get 'get_wikipedia_image' , on: :collection
    get 'load_page' , on: :collection
    post 'join'
    get 'suggest' , on: :collection
    post 'add_to_queue', on: :collection
    get 'download_playlist', on: :collection
    get 'download_multiple', on: :collection
  end

  resources :albums , only: [ :index , :show , :edit , :update ] do
    get 'suggest' , on: :collection
    get 'load_page' , on: :collection
    get 'suggest' , on: :collection
    post 'add_to_queue', on: :collection
    get 'download_playlist', on: :collection
    get 'download_multiple', on: :collection
  end

  resources :play_lists

  resources :radios do
    get 'create_spanish_radios', on: :collection
  end

  resources :tasks , only: [ :index , :new , :create ]

  resource :setting , only: [ :edit , :update ] do
    post 'speech'
    get 'recalculate_metadata'
    get 'start_music_service'
    get 'stop_music_service'
    get 'shutdown'
    get 'mount_usb_drive'
  end

  resource :tools , only: [] do
    get 'youtube', on: :collection
    post 'get_youtube', on: :collection
    get 'duplicated_songs', on: :collection
    get 'readme' , on: :collection
  end

  resources :logs , only: [ :index , :show ] do
    get 'load_page' , on: :collection
    post 'clear' , on: :collection
  end

  root 'player#index'

end

app/models/radio.rb
require_relative './images_module'

# Internet radio information
class Radio < ActiveRecord::Base

  # Functions to handle the radio image
  include ImagesModule

  ###################################################
  # ATTRIBUTES
  ###################################################

  ##
  # :attr_accessor: name
  # Radio name (length = Constants::NAME_MAX_LENGTH)

  ##
  # :attr_accessor: streaming_url
  # Radio streaming url (length = Constants::URL_MAX_LENGTH)

  ##
  # :attr_accessor: web_url
  # Radio web site url. It can be nil (length = Constants::URL_MAX_LENGTH)

  ###################################################
  # VALIDATIONS
  ###################################################

  validates :name, presence: true , length: { maximum: Constants::NAME_MAX_LENGTH }
  validates :streaming_url , presence: true , length: { maximum: Constants::URL_MAX_LENGTH }

  ###################################################
  # MEMBERS
  ###################################################

  # Get the next/previous Radio
  # [+current_radio+] The current Radio. It can be nil
  # [+direction+] The direction to search:
  # * +:forward+ Search forward
  # * +:backward+ Search backward
  # [+returns+] The next Radio
  # If now there are no radios, it returns nil
  def self.next_radio( current_radio, direction = :forward )

    return bound_radio(direction) if !current_radio

    txt_order = ( direction == :forward ? 'name > ?' : 'name < ?' )
    next_radio = query_next_radio(direction)
      .where( txt_order , current_radio.name )
      .take

    next_radio = bound_radio(direction) if !next_radio

    return next_radio
  end

  # Get the radio to play when trying to play a given radio
  # [+radio+] The Radio to check. It can be nil
  # [+returns+] The Radio to play. nil if there are no radios.
  def self.start_radio(radio = nil)
    if !radio || !Radio.exists?(id: radio.id)
      # Restart from the beginning
      return bound_radio
    else
      return radio
    end
  end

  # Get the radio to play when trying to play a given radio
  # [+radio_id+] The Integer of the Radio id to check
  # [+returns+] The Radio to play. nil if there is no radio.
  def self.start_radio_id(radio_id = nil)
    return start_radio( Radio.find_by_id( radio_id ) )
  end

  ###################################################################
  private
  ###################################################################

  # Returns a query to search radios a given direction
  # [+direction+] Direction for the query order +:forward+ or +:backward+
  # [+returns+] The active record query with the order set
  def self.query_next_radio(direction = :forward)
    query = Radio.all
    if direction == :forward
      query = query.order(:name)
    else
      query = query.order(name: :desc)
    end
    return query
  end

  # Get the first or last song of the list
  # [+direction+] If it's +:forward+, it will return the first song. If it's
  # +:backward+, it will return the last song
  # [+returns+] The given PlayListSong
  def self.bound_radio(direction = :forward)
    return query_next_radio(direction).take
  end

end

app/controllers/radios_controller.rb
require_relative '../../lib/music/meta_generation'

# Work with radios controller
class RadiosController < MusicBaseController

  include SpanishRadiosModule

  # Index page
  def index
    render_index
  end

  # Show a radio action
  def show
    @radio = Radio.find( params[:id] )
  end

  # Create new radio
  def new
    @radio = Radio.new
    render 'form'
  end

  # Save a new radio
  def create
    @radio = Radio.new( play_list_params )
    if @radio.save
      store_radio_image
    end
    check_errors_edit
  end

  # Edit a radio
  def edit
    @radio = Radio.find( params[:id] )
    render 'form'
  end

  # Update a radio
  def update
    @radio = Radio.find(params[:id])
    old_name = @radio.name
    if @radio.update(play_list_params)
      if old_name != @radio.name
        # Update the image file names
        @radio.rename_image_files(old_name)
      end
      store_radio_image
    end
    check_errors_edit
  end

  # Delete a radio
  def destroy
    result = execute_music_cmd( :delete_radio , { radio_ids: [ params[:id].to_i ] } )
    if result.status == :success
      redirect_to radios_path
    else
      @radio = Radio.find( params[:id] )
      @radio.errors.add(:base , result.info )
      render 'form'
    end
  end

  # Create some spanish radios
  def create_spanish_radios
    spanish_radios.each do |radio_info|
      if !Radio.where(name: radio_info[:name]).any?
        r = Radio.new
        r.name = radio_info[:name]
        r.streaming_url = radio_info[:streaming_url]
        r.web_url = radio_info[:web_url]
        r.save

        if radio_info[:image_url]
          # Try to save the radio image
          begin
            MetaGeneration.download_artist_image(r, radio_info[:image_url])
          rescue
            Log.log_last_exception
          end
        end
      end
    end
    redirect_to radios_path
  end

  ###############################################
  protected
  ###############################################

  def check_errors_edit
    if @radio.errors.any?
      render 'form'
    else
      redirect_to radios_path
    end
  end

  # Store the radio image
  def store_radio_image
    ArtistsController.store_image(self, @radio)
  end

  def play_list_params
    params.require(:radio).permit(:name, :streaming_url, :web_url)
  end

  def render_index
    @radios = Radio.all.order(:name)
    # Get the content of the artist images directory
    @images_list = ImagesModule.images_dir_list
    render 'index'
  end

end

app/helpers/radios_helper.rb
module RadiosHelper
end

app/views/radios/_table.html.erb
<%#
  Renders a table with all radios
  PARAMS:
  show_edit: Show the edit button? Default is false
%>

<%
  show_edit = false if local_assigns[:show_edit].nil?
%>

<table id="radios" class="table" style="width:100%">
  <thead>
    <tr>
      <th class="hidden-xs">Image</th>
      <th style="width:100%">Name</th>
      <% if show_edit %>
        <th></th>
      <% end %>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @radios.each do |r| %>
      <tr id="radio_<%= r.id %>">
        <td class="image_cell hidden-xs">
          <%= render 'artists/artist_image' ,
            { artist: r , show_cross: true , span_class: 'img_container_small' ,
              images_list: @images_list } %>
        </td>
        <td class="vert_center">
          <%= link_to r.name, radio_path(r) %>
        </td>
        <% if show_edit %>
          <td class="vert_center">
            <%= link_to edit_radio_path(r) , class: 'btn btn-default' , title: 'Edit radio' do %>
              <span class="glyphicon glyphicon-edit"></span>
            <% end %>
          </td>
        <% end %>
        <td class="vert_center">
          <%= link_to music_cmd_player_path(
            { cmd: :play_radio , radio_id: r.id } ), remote: true,
            class: 'btn btn-default' , title: 'Play radio' do %>
            <span class="glyphicon glyphicon-play"></span>
          <% end %>
        </td>
    <% end %>
  </tbody>
</table>

app/views/radios/form.html.erb
<% content_for :title, 'Edit radio ' + ( @radio.name ? @radio.name : '' ) %>
<h1>Radio</h1>

<%= render 'shared/form_messages' , { messages: @radio.errors } %>

<%= form_for @radio do |f| %>

  <div class="form-group">
    <%= f.label :name , class: 'control-label' %>
    <%= f.text_field :name , class: 'form-control' ,
      maxlength: Constants::NAME_MAX_LENGTH , placeholder: 'Radio name' %>
  </div>

  <div class="form-group">
    <%= f.label :streaming_url , class: 'control-label' %>
    <%= f.text_field :streaming_url , class: 'form-control' ,
      maxlength: Constants::URL_MAX_LENGTH , placeholder: 'Radio mp3 streaming URL' %>
  </div>

  <div class="form-group">
    <%= f.label :web_url , class: 'control-label' %>
    <%= f.text_field :web_url , class: 'form-control' ,
      maxlength: Constants::URL_MAX_LENGTH , placeholder: 'Radio web site URL. Optional' %>
  </div>

  <%# Radio image edition %>
  <%= render 'artists/edit_image' , { instance: @radio } %>

  <%= f.submit class: 'btn btn-primary' %>

  <% if params[:action] != 'new' && params[:action] != 'create' %>
    <%= link_to radio_path( @radio ) ,
      method: :delete,
      data: { confirm: 'Are you sure you want to delete the radio?' },
      class: 'btn btn-danger' do %>
      <span class="glyphicon glyphicon-remove"></span> Delete radio
    <% end %>
  <% end %>

<% end %>

<%# Initialize the page %>
<%= javascript_tag do %>
  pageState.setPage(radioEditPage);
<% end %>

app/views/radios/index.html.erb
<% content_for :title, 'Radios' %>
<h1>Radios (<%= @radios.length %>)</h1>

<%# General operations %>
<p>
  <%= link_to new_radio_path , class:'btn btn-default' do %>
    <span class="glyphicon glyphicon-plus"></span> New radio
  <% end %>

  <%= link_to create_spanish_radios_radios_path , class:'btn btn-default' ,
    data: { confirm: 'Are you sure you want to create some spanish radios?' } do %>
    <span class="glyphicon glyphicon-plus"></span> Create some spanish radios
  <% end %>
</p>

<%= render 'table' , { show_edit: true } %>

app/views/radios/show.html.erb
<% content_for :title, @radio.name %>

<h1><%= @radio.name %></h1>
<p style="text-align: center">
  <%= render 'artists/artist_image' , { artist: @radio , size: :medium ,
    img_class: 'img_100' } %>
</p>

<dl>
  <% if @radio.web_url && !@radio.web_url.empty? %>
    <dt>Web URL</dt>
    <dd>
      <%= link_to @radio.web_url , @radio.web_url , target: '_blank' %>
    </dd>
  <% end %>

  <dt>Streaming URL</dt>
  <dd>
    <%= link_to @radio.streaming_url, @radio.streaming_url, target: '_blank' %>
  </dd>
</dl>

<%= link_to music_cmd_player_path(
  { cmd: :play_radio , radio_id: @radio.id } ), remote: true,
  class: 'btn btn-default' , title: 'Play radio' do %>
  <span class="glyphicon glyphicon-play"></span>
  <span class="hidden-xs">Play</span>
<% end %>

<%= link_to edit_radio_path(@radio) , class:'btn btn-default' do %>
  <span class="glyphicon glyphicon-edit"></span>
  <span class="hidden-xs">Edit</span>
<% end %>